### ISSUE TITLE
Remove or Document Unused Attributes in UniqueListingList Class

### ISSUE THREAD

**Issue by BuffWuff1712** [AY2425S1-CS2103T-F15-3/tp#153]
![Screenshot 2024-10-30 011918](https://github.com/user-attachments/assets/a21cf74a-cace-4e29-9ddc-3c6df70d799d)
The UniqueListingList class currently has several attributes (hdbCount, landedCount, and condoCount) that are not utilised anywhere in the code.

**Comment by Tkaixiang** [comment]
Fixed in #214
