### ISSUE TITLE
PROperty version in the Java program not updated

### ISSUE THREAD

**Issue by sayomaki** [AY2425S1-CS2103T-F15-3/tp#171]
Currently, the latest release version of PROperty is 1.4, and this value is not updated in the java application, as seen below:

https://github.com/AY2425S1-CS2103T-F15-3/tp/blob/29686b840bb41948db75aecd51325afe2cbbf8e8/src/main/java/seedu/address/MainApp.java#L39

**Comment by Tkaixiang** [comment]
Fixed in #224
