### ISSUE TITLE
Add command accepts numbers for name field

### ISSUE THREAD

**Issue by Vatinius** [AY2425S1-CS2103T-F15-3/tp#188]
Currently, the user can input numbers into the name field and PROperty will accept it as a valid input. For example,

![image](https://github.com/user-attachments/assets/b35418ac-a597-471f-8b9f-2e10bb797b12)

**Comment by Tkaixiang** [comment]
Marked as won't fix, since some names can indeed have numbers 
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
