### ISSUE TITLE
[PE-D][Tester C] Double-clicking does not start the app.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-3/tp#235]
User guide states that users can double click the jar file to start up the app.

![image.png](https://raw.githubusercontent.com/hj235/ped/main/files/db52ac02-eb66-423e-b5a3-39ee0ab2a368.png)

However, doing so raises an error by the JVM Launcher.

To recreate: Double click the jar file in a separate folder.

![image.png](https://raw.githubusercontent.com/hj235/ped/main/files/dfb25acf-1c5f-4f0b-9cc7-99c8a137923d.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: hj235/ped#1

**Comment by sayomaki** [comment]
Hi @hj235, thanks for reporting the issue! We have noted this problem and found that it may actually be an association error with your Java installation.

The jar file has been tested by all the members in our team on their own machines (both Windows and MacOS), and we can confirm that double-clicking the jar file works and launches the program as intended.

Could you please kindly check if your system java installation is correct, i.e. followed the [instructions from the CS2103T/SE-EDU website](https://se-education.org/guides/tutorials/javaInstallationWindows.html) on java installation, and then see if you can reproduce the error?

Also, another thing to note is that your icon appears different from ours, I have done a fresh installation of Java 17 on a new machine following the official guide on SE-EDU, and this is how it looks like:

<img width="811" alt="image" src="https://github.com/user-attachments/assets/19ab409c-b128-43ed-ab1e-15df3f2c8b73">

Thank you for submitting this issue, and if you need further clarifications feel free to reply here!

**Comment by Tkaixiang** [comment]
Will add this to the User Guide that the recommended way to open PROperty is still to use the command line
