### ISSUE TITLE
[PE-D][Tester C] Truncation of details using show command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-3/tp#241]
As specified in the UG, show command is intended to show full details of an entry.

![image.png](https://raw.githubusercontent.com/hj235/ped/main/files/691bd150-75cc-4b77-8d1c-72c624f1b4e9.png)

However, if the name or email is too long, the details will end up being truncated. Whereas, the other fields are wrapped around to the next line instead.

![image.png](https://raw.githubusercontent.com/hj235/ped/main/files/24769e0a-6193-4c42-85e8-d13399b294d0.png)

To recreate:
Add a person with a name and email long enough to extend past the window's size and be truncated. Then show the person using the show [INDEX] command.
If the name and email fields are not long enough, edit the person until these fields become truncated.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: hj235/ped#2

**Comment by tayxuenye** [comment]
![Screenshot 2024-11-09 155757](https://github.com/user-attachments/assets/c2cd5fb3-61b2-4d17-9541-c39732c020bd)

**Comment by tayxuenye** [comment]
This falls under Q8 as shown in comment above. So it is not a bug.
