### ISSUE TITLE
[PE-D][Tester B] Default text for no remarks

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#243]
For all fields, if there is no data it is left blank. However, the remark field has a default remark of "A remark" for the pre-existing contacts 

![Screenshot 2024-11-08 at 4.29.06 PM.png](https://raw.githubusercontent.com/SherChew27/ped/main/files/a3948c21-fd72-4e03-ac6b-94d9eb56c241.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: SherChew27/ped#4

**Comment by tayxuenye** [comment]
I tried adding a new person and don't face this issue. Not sure what he means.

**Comment by Tkaixiang** [comment]
Not a bug, the default contacts have the literal string "A Remark" as a form of testing, clients without a remark will not show a remark field
