### ISSUE TITLE
[PE-D][Tester B] Missing Header for UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#245]
The name of the product should be prominently displayed at the top of the UG.
![Screenshot 2024-11-08 at 4.31.42 PM.png](https://raw.githubusercontent.com/SherChew27/ped/main/files/c927af69-3b81-454e-a35d-e744e3b0f33c.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: SherChew27/ped#6

**Comment by BuffWuff1712** [comment]
Not exactly a doc bug, but title could be improved
