### ISSUE TITLE
[PE-D][Tester C] A person with s/o in their name cannot be added

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#247]
Some people could have s/o or d/o in their name, however the app does not allow this behavior.

![image.png](https://raw.githubusercontent.com/hj235/ped/main/files/5592ac88-ca47-4a3d-a014-d9194225de90.png)

To recreate:
Enter the command as shown in the screenshot

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: hj235/ped#3

**Comment by tayxuenye** [comment]
Not a bug. Already anticipated input. Duplicate issue.
