### ISSUE TITLE
[PE-D][Tester B] Inconsistent command format

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#255]
For commands such as findtag, the parameter does not need the "t/" prefix. For other commands such as listing add, it required the "t/" prefix.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: SherChew27/ped#11

**Comment by BuffWuff1712** [comment]
not v sure what this means

**Comment by tayxuenye** [comment]
not a bug. we cannot change command format now.
