### ISSUE TITLE
[PE-D][Tester E] Incorrect notation used in Logic Component diagrams

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-3/tp#276]
The double arrow notation used in the diagrams under the Logic Component diagram is an invalid UML notation.

It would be more appropriate to use association labels instead.

![image.png](https://raw.githubusercontent.com/yong-zhuo/ped/main/files/03cc423a-9262-4dbb-89b7-e4c3980fba7b.png)

![image.png](https://raw.githubusercontent.com/yong-zhuo/ped/main/files/29162abd-23c2-48b7-9da9-e762d9555d6b.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: yong-zhuo/ped#10

**Comment by BuffWuff1712** [comment]
I don't think there's an issue upon further analysis
