### ISSUE TITLE
[PE-D][Tester B] Unnecessary field

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#295]
Address field for the client is no longer relevant as the listing address is alr noted.
![Screenshot 2024-11-08 at 5.22.21 PM.png](https://raw.githubusercontent.com/SherChew27/ped/main/files/abcb098e-ecf1-4ef1-bd92-49736233a219.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: SherChew27/ped#18

**Comment by Tkaixiang** [comment]
Not a bug, the address field and listing address fields represent different data
One is the client's own address, the listing address might/might not be an address the client is staying at
