### ISSUE TITLE
[PE-D][Tester E] Shown contact details is still being displayed after clearing all contacts

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#303]
## Details
Users are still able to view a client's details that is being shown on the right even after clearing all the contacts using the `clear` command.

 As the contact no longer exist in the app, their details should no longer be displayed for others to view as it could mislead users to believe that the person's data still exists in the app.

## Steps to reproduce bug
1. Type `show 4` to show the contact details at index 4
![image.png](https://raw.githubusercontent.com/yong-zhuo/ped/main/files/b9c20414-a405-45be-abc6-ad56f8f908db.png)

2. Type `clear`

3. Able to still view the previously shown contact details even though their details should no longer exist in the system after clearing
![image.png](https://raw.githubusercontent.com/yong-zhuo/ped/main/files/227a94bd-6a3b-464a-a33c-19eb8ebe4036.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yong-zhuo/ped#16

**Comment by sayomaki** [comment]
Might not be a functionality bug as the person shown adheres to design, that it will show the person as part of the show command until showing a different person.

Users can just restart the app, or show a different person using the `show` command, and this is considered just a minor inconvenience.
