### ISSUE TITLE
[PE-D][Tester C] Use case not aligned with product

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#308]
The following use case as shown in the DG says that users can request for suggestions for tags, and the app provides them with a list of suggested tags. However, in the application and in the UG, no such feature is shown.

![image.png](https://raw.githubusercontent.com/hj235/ped/main/files/6e18022b-2b19-4553-a59e-6eff0a32a7bd.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: hj235/ped#16

**Comment by tayxuenye** [comment]
Will remove
