### ISSUE TITLE
[PE-D][Tester C] Missing feature tour from DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#309]
The DG describes a use case where the user can go through a 'feature tour' guided step-by-step by the application. However, no such feature is implemented in the app, nor is it described in the UG.

![image.png](https://raw.githubusercontent.com/hj235/ped/main/files/6d1c5421-25c5-41cf-962f-159c6bb22648.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: hj235/ped#17

**Comment by tayxuenye** [comment]
Will remove
