### ISSUE TITLE
[PE-D][Tester A] Uses case combining 2 different scenario

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#321]
In the use case: Set reminders and see upcoming events, it contains both use case to set reminder and to view upcoming reminder. It would be better if it was seperated into 1)set reminders and 2)View reminders.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: DesSnowy/ped#19

**Comment by tayxuenye** [comment]
Removed use cases.
