### ISSUE TITLE
Release v1.3 on Github

### ISSUE THREAD

**Issue by tayxuenye** [AY2425S1-CS2103T-F15-3/tp#77]
Write a fairly detailed Release Note in the text field GitHub provides for the description of the release. In particular, describe what has been changed (compared to AB3). This is just an itemized list of What's New -- no need to be as elaborate as a user guide.
Include screenshots (or screen recordings) of your product in action, featuring the changes you've done.
 These release notes will be checked by the teaching team to verify (a) that they are written reasonably well, and, (b) that the features mentioned in there show the product has reached the MVP level of functionality.
Upload the JAR file as well. Instructions for creating a JAR file can be found in [as described in the tP Developer Guide](https://nus-cs2103-ay2425s1.github.io/tp/DevOps.html#making-a-release).

**Comment by Vatinius** [comment]
Link to release notes draft:
https://docs.google.com/document/d/1_6WMhnk5QEzh2UOsdbNtDuNzsblTyIQheQCrci7cJps/edit?usp=sharing

**Comment by Tkaixiang** [comment]
Released
